import type { AstroComponentFactory } from "astro/runtime/server/index.js";
import type { PageAstroInstance, SitePages } from "helpers/types";

export const filteredPagesMockData: PageAstroInstance[] = [
  {
    url: "",
    title: "Home",
    keywords: "Neo landing page",
    default: {} as AstroComponentFactory,
    file: "",
  } as PageAstroInstance,
  {
    url: "/about",
    title: "About",
    keywords: "About page",
    default: {} as AstroComponentFactory,
    file: "",
  } as PageAstroInstance,
  {
    url: "/contact",
    title: "Contact",
    keywords: "Contact page",
    default: {} as AstroComponentFactory,
    file: "",
  } as PageAstroInstance,
];

export const allPagesMockData: SitePages = {
  accessibility: [
    {
      default: {} as AstroComponentFactory,
      file: "/Users/enriquep/dev/design-portal/src/pages/accessibility/principles.astro",
      url: "/accessibility/principles",
      title: "Principles",
      keywords: "principle component",
    } as PageAstroInstance,
    {
      default: {} as AstroComponentFactory,
      file: "/Users/enriquep/dev/design-portal/src/pages/accessibility/resources-guides.astro",
      url: "/accessibility/resources-guides",
      title: "Resources and Guides",
      keywords: "resources guides",
    } as PageAstroInstance,
    {
      default: {} as AstroComponentFactory,
      file: "/Users/enriquep/dev/design-portal/src/pages/accessibility/testing-tools.astro",
      url: "/accessibility/testing-tools",
      title: "Testing Tools",
      keywords: "Testing Tools",
    } as PageAstroInstance,
  ],
  components: [
    {
      default: {} as AstroComponentFactory,
      file: "/Users/enriquep/dev/design-portal/src/pages/components/accordion.astro",
      url: "/components/accordion",
      title: "Accordion",
      keywords: "stack stacked menu expandable component",
    } as PageAstroInstance,
  ],
  docs: [],
  guidelines: [],
};

export const allActualPagesUnsorted: SitePages = {
  accessibility: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/testing-tools.astro",
      url: "/accessibility/testing-tools",
      title: "Testing Tools",
      keywords: "Testing Tools",
      order: 4,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/principles.astro",
      url: "/accessibility/principles",
      title: "Principles",
      keywords: "principle component",
      order: 1,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/resources-guides.astro",
      url: "/accessibility/resources-guides",
      title: "Resources and Guides",
      keywords: "resources guides",
      order: 2,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/keyboard-interactions.astro",
      url: "/accessibility/keyboard-interactions",
      title: "Keyboard Interactions",
      keywords: "accessbility, a11y, keyboard, interactions",
      order: 5,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/product-team-guides.astro",
      url: "/accessibility/product-team-guides",
      title: "Product Team Guides",
      keywords:
        "accessibility, product, team, guide, visual, design, development, quality, assurance",
      order: 3,
    } as PageAstroInstance,
  ],
  components: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/accordion.astro",
      url: "/components/accordion",
      title: "Accordion",
      keywords: "stack stacked menu expandable component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/avatar.astro",
      url: "/components/avatar",
      title: "Avatar",
      keywords: "avatar image icon menu component list item",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/badge.astro",
      url: "/components/badge",
      title: "Badge",
      keywords: "component badge notification",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/breadcrumb.astro",
      url: "/components/breadcrumb",
      title: "Breadcrumb",
      keywords: "component breadcrumb navigation",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/buttons.astro",
      url: "/components/buttons",
      title: "Button",
      keywords: "component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/checkbox.astro",
      url: "/components/checkbox",
      title: "Checkbox",
      keywords: "checkbox checkboxes component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/chip.astro",
      url: "/components/chip",
      title: "Chip",
      keywords: "chips components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/design-tokens.astro",
      url: "/components/design-tokens",
      title: "Design Tokens",
      keywords: "design token components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/dropdown.astro",
      url: "/components/dropdown",
      title: "Dropdown",
      keywords: "dropdown components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/form.astro",
      url: "/components/form",
      title: "Form",
      keywords: "form layout component container forms",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/header.astro",
      url: "/components/header",
      title: "Header",
      keywords: "topnav header component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/icon.astro",
      url: "/components/icon",
      title: "Icon",
      keywords: "component icon",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/image.astro",
      url: "/components/image",
      title: "Image",
      keywords: "img thumbnail components visual photo illustration",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/link.astro",
      url: "/components/link",
      title: "Link",
      keywords: "Link",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/list.astro",
      url: "/components/list",
      title: "List",
      keywords: "list component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/modal.astro",
      url: "/components/modal",
      title: "Modal",
      keywords: "modal",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/notifications.astro",
      url: "/components/notifications",
      title: "Notifications",
      keywords: "notification notifications component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/pagination.astro",
      url: "/components/pagination",
      title: "Pagination",
      keywords: "pagination component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/radio.astro",
      url: "/components/radio",
      title: "Radio",
      keywords: "radio group radiogroup components multichoice",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/select.astro",
      url: "/components/select",
      title: "Select",
      keywords: "select selectbox combobox multiselect dropdown component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/sheet.astro",
      url: "/components/sheet",
      title: "Sheet",
      keywords: "sheet overlay panel context component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/shimmer.astro",
      url: "/components/shimmer",
      title: "Shimmer",
      keywords: "Shimmer components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/side-navigation.astro",
      url: "/components/side-navigation",
      title: "Side Navigation",
      keywords: "topnav header navigation link component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/spinner.astro",
      url: "/components/spinner",
      title: "Spinner",
      keywords: "spinner component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/switch.astro",
      url: "/components/switch",
      title: "Switch",
      keywords: "switch component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/table.astro",
      url: "/components/table",
      title: "Table",
      keywords: "table component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tabs.astro",
      url: "/components/tabs",
      title: "Tabs",
      keywords: "tabs component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/text-input.astro",
      url: "/components/text-input",
      title: "Text Input",
      keywords: "text input area textarea textinput password component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/theme.astro",
      url: "/components/theme",
      title: "Theme",
      keywords: "Theme component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/toast.astro",
      url: "/components/toast",
      title: "Toast",
      keywords: "toast component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tooltip.astro",
      url: "/components/tooltip",
      title: "Tooltip",
      keywords: "Tooltip components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tree-view.astro",
      url: "/components/tree-view",
      title: "Tree View",
      keywords: "tree view component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/widget.astro",
      url: "/components/widget",
      title: "Widget",
      keywords: "widget component",
      order: undefined,
    } as PageAstroInstance,
  ],
  docs: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/changelog.astro",
      url: "/docs/changelog",
      title: "Changelog",
      keywords: "changelog css react design system docs",
      order: 2,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/setup.astro",
      url: "/docs/setup",
      title: "Setup Neo",
      keywords:
        "docs setup neo react css npm node package manager npm pnpm yarn",
      order: 1,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/faqs.astro",
      url: "/docs/faqs",
      title: "FAQs",
      keywords: "frequently asked questions faqs docs",
      order: 3,
    } as PageAstroInstance,
  ],
  guidelines: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/color.astro",
      url: "/guidelines/color",
      title: "Color",
      keywords: "color priniciples library accessibility",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/data-visualization.astro",
      url: "/guidelines/data-visualization",
      title: "Data Visualization",
      keywords: "data visualization chart analytics report",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/overview.astro",
      url: "/guidelines/overview",
      title: "Overview",
      keywords: "Guidelines for building applications",
      order: 1,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/layout-grid.astro",
      url: "/guidelines/layout-grid",
      title: "Layout and Grid",
      keywords: "Layout Grid",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/internationalization.astro",
      url: "/guidelines/internationalization",
      title: "Internationalization",
      keywords: "internationalization",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/motion.astro",
      url: "/guidelines/motion",
      title: "Motion",
      keywords: "motion animation dynamic movement css",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/platform.astro",
      url: "/guidelines/platform",
      title: "Platform",
      keywords: "platform web ios windows mac android",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/sound.astro",
      url: "/guidelines/sound",
      title: "Sound",
      keywords: "Guidelines for building applications",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/typography.astro",
      url: "/guidelines/typography",
      title: "Typography",
      keywords: "Typography Guidelines",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/voice-tone.astro",
      url: "/guidelines/voice-tone",
      title: "Voice and Tone",
      keywords: "voice tone",
      order: undefined,
    } as PageAstroInstance,
  ],
};
export const allActualPagesSorted: SitePages = {
  accessibility: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/principles.astro",
      url: "/accessibility/principles",
      title: "Principles",
      keywords: "principle component",
      order: 1,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/resources-guides.astro",
      url: "/accessibility/resources-guides",
      title: "Resources and Guides",
      keywords: "resources guides",
      order: 2,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/product-team-guides.astro",
      url: "/accessibility/product-team-guides",
      title: "Product Team Guides",
      keywords:
        "accessibility, product, team, guide, visual, design, development, quality, assurance",
      order: 3,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/testing-tools.astro",
      url: "/accessibility/testing-tools",
      title: "Testing Tools",
      keywords: "Testing Tools",
      order: 4,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/keyboard-interactions.astro",
      url: "/accessibility/keyboard-interactions",
      title: "Keyboard Interactions",
      keywords: "accessbility, a11y, keyboard, interactions",
      order: 5,
    } as PageAstroInstance,
  ],
  components: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/accordion.astro",
      url: "/components/accordion",
      title: "Accordion",
      keywords: "stack stacked menu expandable component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/avatar.astro",
      url: "/components/avatar",
      title: "Avatar",
      keywords: "avatar image icon menu component list item",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/badge.astro",
      url: "/components/badge",
      title: "Badge",
      keywords: "component badge notification",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/breadcrumb.astro",
      url: "/components/breadcrumb",
      title: "Breadcrumb",
      keywords: "component breadcrumb navigation",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/buttons.astro",
      url: "/components/buttons",
      title: "Button",
      keywords: "component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/checkbox.astro",
      url: "/components/checkbox",
      title: "Checkbox",
      keywords: "checkbox checkboxes component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/chip.astro",
      url: "/components/chip",
      title: "Chip",
      keywords: "chips components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/design-tokens.astro",
      url: "/components/design-tokens",
      title: "Design Tokens",
      keywords: "design token components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/dropdown.astro",
      url: "/components/dropdown",
      title: "Dropdown",
      keywords: "dropdown components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/form.astro",
      url: "/components/form",
      title: "Form",
      keywords: "form layout component container forms",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/header.astro",
      url: "/components/header",
      title: "Header",
      keywords: "topnav header component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/icon.astro",
      url: "/components/icon",
      title: "Icon",
      keywords: "component icon",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/image.astro",
      url: "/components/image",
      title: "Image",
      keywords: "img thumbnail components visual photo illustration",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/link.astro",
      url: "/components/link",
      title: "Link",
      keywords: "Link",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/list.astro",
      url: "/components/list",
      title: "List",
      keywords: "list component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/modal.astro",
      url: "/components/modal",
      title: "Modal",
      keywords: "modal",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/notifications.astro",
      url: "/components/notifications",
      title: "Notifications",
      keywords: "notification notifications component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/pagination.astro",
      url: "/components/pagination",
      title: "Pagination",
      keywords: "pagination component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/radio.astro",
      url: "/components/radio",
      title: "Radio",
      keywords: "radio group radiogroup components multichoice",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/select.astro",
      url: "/components/select",
      title: "Select",
      keywords: "select selectbox combobox multiselect dropdown component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/sheet.astro",
      url: "/components/sheet",
      title: "Sheet",
      keywords: "sheet overlay panel context component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/shimmer.astro",
      url: "/components/shimmer",
      title: "Shimmer",
      keywords: "Shimmer components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/side-navigation.astro",
      url: "/components/side-navigation",
      title: "Side Navigation",
      keywords: "topnav header navigation link component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/spinner.astro",
      url: "/components/spinner",
      title: "Spinner",
      keywords: "spinner component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/switch.astro",
      url: "/components/switch",
      title: "Switch",
      keywords: "switch component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/table.astro",
      url: "/components/table",
      title: "Table",
      keywords: "table component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tabs.astro",
      url: "/components/tabs",
      title: "Tabs",
      keywords: "tabs component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/text-input.astro",
      url: "/components/text-input",
      title: "Text Input",
      keywords: "text input area textarea textinput password component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/theme.astro",
      url: "/components/theme",
      title: "Theme",
      keywords: "Theme component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/toast.astro",
      url: "/components/toast",
      title: "Toast",
      keywords: "toast component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tooltip.astro",
      url: "/components/tooltip",
      title: "Tooltip",
      keywords: "Tooltip components",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tree-view.astro",
      url: "/components/tree-view",
      title: "Tree View",
      keywords: "tree view component",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/widget.astro",
      url: "/components/widget",
      title: "Widget",
      keywords: "widget component",
      order: undefined,
    } as PageAstroInstance,
  ],
  docs: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/setup.astro",
      url: "/docs/setup",
      title: "Setup Neo",
      keywords:
        "docs setup neo react css npm node package manager npm pnpm yarn",
      order: 1,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/changelog.astro",
      url: "/docs/changelog",
      title: "Changelog",
      keywords: "changelog css react design system docs",
      order: 2,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/faqs.astro",
      url: "/docs/faqs",
      title: "FAQs",
      keywords: "frequently asked questions faqs docs",
      order: 3,
    } as PageAstroInstance,
  ],
  guidelines: [
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/overview.astro",
      url: "/guidelines/overview",
      title: "Overview",
      keywords: "Guidelines for building applications",
      order: 1,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/color.astro",
      url: "/guidelines/color",
      title: "Color",
      keywords: "color priniciples library accessibility",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/data-visualization.astro",
      url: "/guidelines/data-visualization",
      title: "Data Visualization",
      keywords: "data visualization chart analytics report",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/layout-grid.astro",
      url: "/guidelines/layout-grid",
      title: "Layout and Grid",
      keywords: "Layout Grid",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/internationalization.astro",
      url: "/guidelines/internationalization",
      title: "Internationalization",
      keywords: "internationalization",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/motion.astro",
      url: "/guidelines/motion",
      title: "Motion",
      keywords: "motion animation dynamic movement css",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/platform.astro",
      url: "/guidelines/platform",
      title: "Platform",
      keywords: "platform web ios windows mac android",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/sound.astro",
      url: "/guidelines/sound",
      title: "Sound",
      keywords: "Guidelines for building applications",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/typography.astro",
      url: "/guidelines/typography",
      title: "Typography",
      keywords: "Typography Guidelines",
      order: undefined,
    } as PageAstroInstance,
    {
      file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/voice-tone.astro",
      url: "/guidelines/voice-tone",
      title: "Voice and Tone",
      keywords: "voice tone",
      order: undefined,
    } as PageAstroInstance,
  ],
};
export const allActualPagesFlattenedUnsorted = [
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/testing-tools.astro",
    url: "/accessibility/testing-tools",
    title: "Testing Tools",
    keywords: "Testing Tools",
    order: 4,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/principles.astro",
    url: "/accessibility/principles",
    title: "Principles",
    keywords: "principle component",
    order: 1,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/resources-guides.astro",
    url: "/accessibility/resources-guides",
    title: "Resources and Guides",
    keywords: "resources guides",
    order: 2,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/keyboard-interactions.astro",
    url: "/accessibility/keyboard-interactions",
    title: "Keyboard Interactions",
    keywords: "accessbility, a11y, keyboard, interactions",
    order: 5,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/accessibility/product-team-guides.astro",
    url: "/accessibility/product-team-guides",
    title: "Product Team Guides",
    keywords:
      "accessibility, product, team, guide, visual, design, development, quality, assurance",
    order: 3,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/accordion.astro",
    url: "/components/accordion",
    title: "Accordion",
    keywords: "stack stacked menu expandable component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/avatar.astro",
    url: "/components/avatar",
    title: "Avatar",
    keywords: "avatar image icon menu component list item",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/badge.astro",
    url: "/components/badge",
    title: "Badge",
    keywords: "component badge notification",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/breadcrumb.astro",
    url: "/components/breadcrumb",
    title: "Breadcrumb",
    keywords: "component breadcrumb navigation",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/buttons.astro",
    url: "/components/buttons",
    title: "Button",
    keywords: "component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/checkbox.astro",
    url: "/components/checkbox",
    title: "Checkbox",
    keywords: "checkbox checkboxes component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/chip.astro",
    url: "/components/chip",
    title: "Chip",
    keywords: "chips components",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/design-tokens.astro",
    url: "/components/design-tokens",
    title: "Design Tokens",
    keywords: "design token components",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/dropdown.astro",
    url: "/components/dropdown",
    title: "Dropdown",
    keywords: "dropdown components",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/form.astro",
    url: "/components/form",
    title: "Form",
    keywords: "form layout component container forms",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/header.astro",
    url: "/components/header",
    title: "Header",
    keywords: "topnav header component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/icon.astro",
    url: "/components/icon",
    title: "Icon",
    keywords: "component icon",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/image.astro",
    url: "/components/image",
    title: "Image",
    keywords: "img thumbnail components visual photo illustration",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/link.astro",
    url: "/components/link",
    title: "Link",
    keywords: "Link",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/list.astro",
    url: "/components/list",
    title: "List",
    keywords: "list component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/modal.astro",
    url: "/components/modal",
    title: "Modal",
    keywords: "modal",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/notifications.astro",
    url: "/components/notifications",
    title: "Notifications",
    keywords: "notification notifications component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/pagination.astro",
    url: "/components/pagination",
    title: "Pagination",
    keywords: "pagination component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/radio.astro",
    url: "/components/radio",
    title: "Radio",
    keywords: "radio group radiogroup components multichoice",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/select.astro",
    url: "/components/select",
    title: "Select",
    keywords: "select selectbox combobox multiselect dropdown component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/sheet.astro",
    url: "/components/sheet",
    title: "Sheet",
    keywords: "sheet overlay panel context component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/shimmer.astro",
    url: "/components/shimmer",
    title: "Shimmer",
    keywords: "Shimmer components",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/side-navigation.astro",
    url: "/components/side-navigation",
    title: "Side Navigation",
    keywords: "topnav header navigation link component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/spinner.astro",
    url: "/components/spinner",
    title: "Spinner",
    keywords: "spinner component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/switch.astro",
    url: "/components/switch",
    title: "Switch",
    keywords: "switch component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/table.astro",
    url: "/components/table",
    title: "Table",
    keywords: "table component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tabs.astro",
    url: "/components/tabs",
    title: "Tabs",
    keywords: "tabs component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/text-input.astro",
    url: "/components/text-input",
    title: "Text Input",
    keywords: "text input area textarea textinput password component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/theme.astro",
    url: "/components/theme",
    title: "Theme",
    keywords: "Theme component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/toast.astro",
    url: "/components/toast",
    title: "Toast",
    keywords: "toast component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tooltip.astro",
    url: "/components/tooltip",
    title: "Tooltip",
    keywords: "Tooltip components",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/tree-view.astro",
    url: "/components/tree-view",
    title: "Tree View",
    keywords: "tree view component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/components/widget.astro",
    url: "/components/widget",
    title: "Widget",
    keywords: "widget component",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/changelog.astro",
    url: "/docs/changelog",
    title: "Changelog",
    keywords: "changelog css react design system docs",
    order: 2,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/setup.astro",
    url: "/docs/setup",
    title: "Setup Neo",
    keywords: "docs setup neo react css npm node package manager npm pnpm yarn",
    order: 1,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/docs/faqs.astro",
    url: "/docs/faqs",
    title: "FAQs",
    keywords: "frequently asked questions faqs docs",
    order: 3,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/color.astro",
    url: "/guidelines/color",
    title: "Color",
    keywords: "color priniciples library accessibility",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/data-visualization.astro",
    url: "/guidelines/data-visualization",
    title: "Data Visualization",
    keywords: "data visualization chart analytics report",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/overview.astro",
    url: "/guidelines/overview",
    title: "Overview",
    keywords: "Guidelines for building applications",
    order: 1,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/layout-grid.astro",
    url: "/guidelines/layout-grid",
    title: "Layout and Grid",
    keywords: "Layout Grid",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/internationalization.astro",
    url: "/guidelines/internationalization",
    title: "Internationalization",
    keywords: "internationalization",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/motion.astro",
    url: "/guidelines/motion",
    title: "Motion",
    keywords: "motion animation dynamic movement css",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/platform.astro",
    url: "/guidelines/platform",
    title: "Platform",
    keywords: "platform web ios windows mac android",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/sound.astro",
    url: "/guidelines/sound",
    title: "Sound",
    keywords: "Guidelines for building applications",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/typography.astro",
    url: "/guidelines/typography",
    title: "Typography",
    keywords: "Typography Guidelines",
    order: undefined,
  } as PageAstroInstance,
  {
    file: "/Users/jsebast/dev/avaya/design-portal/src/pages/guidelines/voice-tone.astro",
    url: "/guidelines/voice-tone",
    title: "Voice and Tone",
    keywords: "voice tone",
    order: undefined,
  } as PageAstroInstance,
];
