export const updates = [
    {
        version: "0.3.0",
        date: "(March 24th, 2022)",
        sections: [
            {
                whatsChanged: [
                    "resolve security issues for package node-forge",
                    "NEO-770 // Table Filter+Sorting, Part 1",
                    "update deps",
                    "Neo 805 Merge Selects",
                    "NEO-819:Link Item Component(Part 1 and 2)",
                    "NEO-796 // update Image component to handle fallbacks",
                    "Bump prismjs from 1.25.0 to 1.27.0",
                    "Bump url-parse from 1.5.7 to 1.5.10",
                    "improve linting script",
                    "improve ExampleComponent examples",
                    "update deps",
                    "couple small table tweaks per discussion with Matt",
                    "NEO-578 // add \"slide\" to Sheet component",
                    "NEO-849: Fixing rendering issue with IconButton component",
                    "correct the dev-linking section of the readme",
                    "NEO-806 Close left menu after clicking right menu",
                    "add semi-bold weight to \"active\" Switch state, and semi-bold to \"active\" and \"active+hovered\" checkbox-dropdown",
                    "neo-844 fix closable tab keyboard handler",
                    "Neo 619 - Combobox",
                    "Neo 791 agent card component",
                    "NEO-817: Left Navigation component (Part 2 of 3)",
                    "Bump node-forge from 1.2.1 to 1.3.0",
                    "Update Sheet to cover more use cases",
                    "Bump minimist from 1.2.5 to 1.2.6",
                    "update deps, code coverage badges, bump to 0.3.0",
                ],
            },
        ]
    },

    {
        version: "0.2.1",
        date: "(February 22nd, 2022)",
        sections: [
            {
                whatsChanged: [
                    "Neo 563 Navbar Part #1",
                    "add notes on how to publish on our GitHub page",
                    "allow Sheet to take div props",
                    "minor cleanup",
                    "Bump nanoid from 3.1.28 to 3.2.0",
                    "Bump node-fetch from 2.6.5 to 2.6.7",
                    "NEO-617 part1",
                    "NEO-617-part2",
                    "Neo 563 Navbar #2",
                    "update deps",
                    "NEO-617 Part 3: support vertical tabs",
                    "Neo 805 Select part #1",
                    "NEO-799 // allow Menu and related components to take children",
                    "NEO-617 part4 closable tab",
                    "latest version of storybook is exploding for an unknown reason, fixing",
                    "ignore *Types.* files when computing testing coverage",
                    "NEO-797 // allow hover to open Menu",
                    "use same story naming pattern for consistency",
                    "fix typo @avaya-neo/react -> @avaya/neo-react",
                    "move helper methods from SubMenu.tsx to helpers.tsx",
                    "Neo 805 Select #2 - Multiple Select",
                    "NEO-799 // add missing props to Menu component",
                    "NEO-616: Tabs with Carousel, Part 1",
                    "fix test name",
                    "NEO-616 split code and add index file",
                    "better name comparison for child type names",
                    "NEO-616-part3 tests and refactor",
                    "Bump follow-redirects from 1.14.7 to 1.14.8",
                    "NEO-805 PR #3 - MultipleSelect additional stories and tests",
                    "Fix console.log in unit test, improve testing done by unit test",
                    "Bump url-parse from 1.5.3 to 1.5.7",
                ],
            },
        ]
    },

    {
        version: "0.2.0",
        date: "(January 18th, 2022)",
        sections: [
            {
                whatsChanged: [
                    "update readme and fix license warning",
                    "update github CI",
                    "update deps AND adding browserslist",
                    "NEO-618 Native Select part 1",
                    "update readme and ext recs",
                    "NEO-618-Select-part-2",
                    "Updated 3rd-party license text for 0.2 release",
                    "zero funcitonal changes, just minor clean up and sorting",
                    "update checkbox and simplify props",
                    "NEO-632 // update TextInput to match mock in Portal",
                    "NEO-696 // update Button.tsx to take children instead of label",
                    "NEO-618-Select-3b",
                    "NEO-696 // add iconPosition prop to Button component",
                    "NEO-567 // Table: selectable rows",
                    "NEO-775 // fix TextInput issue",
                    "fix all dependabot security issues",
                    "fix final security issue via pointing at a community fix",
                    "NEO-777 // add jest-coverage-badges and add badges to readme",
                    "fix minimist security issue",
                    "update copyright based off of Yolanda's instructions",
                    "updating to latest storybook version caused an error when viewing the root",
                    "remove NativeSelect component",
                    "flatten storybook's stories",
                    "NEO-618 // basic SelectNative implementation",
                    "remove unnecessary imports",
                    "NEO-769 // add \"actions\" to the Table component",
                    "Bump follow-redirects from 1.14.4 to 1.14.7",
                    "streamline publishing the library",
                    "update package json version",
                ],
            },
        ]
    }
];